Feature/chrome history extension
posix4e/webtimemachine pull request #2
Opened 2023-11-12 19:15 UTC by eefh

2023-11-12 19:15 UTC, eefh commented
Added Safari project

2023-11-12 19:16 UTC, posix4e commented
Make sure to remove .ds_store and add to gitignore

2023-11-12 19:44 UTC, posix4e commented
Do you wanna setup the github actions for ci/cd?

2023-11-19 03:35 UTC, posix4e requested changes
Haven’t looked in detail will look. In the meantime

- squash into single commit
- Use git lfs for the images 
- Why did you remove my readme? Change the todo boxes instead

2023-11-19 03:36 UTC, posix4e commented on Web Time Machine Extension/Resources/_locales/en/messages.json
> +    "extension_description": {
Perhaps you can help me with a Description

2023-11-19 03:36 UTC, posix4e commented on Web Time Machine Extension/Resources/background.js
> +    console.log("Received request: ", request);
Probably don’t wanna leave debugging stuff around

2023-11-19 03:37 UTC, posix4e commented on Web Time Machine Extension/Resources/popup.js
> +console.log("Hello World!", browser);
:(

2023-11-19 03:37 UTC, posix4e commented on Web Time Machine Extension/SafariWebExtensionHandler.swift
> +//  SafariWebExtensionHandler.swift
Get rid of all the created by

2023-11-19 03:38 UTC, posix4e commented on Web Time Machine/Shared (App)/Resources/Script.js
> +        document.getElementsByClassName('platform-mac state-on')[0].innerText = "Web Time Machine’s extension is currently on. You can turn it off in the Extensions section of Safari Settings.";
Is this where we show history?

2023-11-19 12:11 UTC, posix4e commented on README.md
Please keep the todo for now

2023-11-19 12:12 UTC, posix4e commented
I’m going to wait for you to tell me it’s ready to review

2023-11-29 02:04 UTC, closed without merging